### PR TITLE
Travis CI sudo: required no longer is

### PR DESCRIPTION
**Pull request by cclauss**
Travis has fully deprecated the sudo tag

### CODE REVIEW

**Comment by alexvicegrab** [comment]
Hi Claus, thanks for contributing, please clear the DCO, by ensuring your commits are signed

**Comment by cclauss** [comment]
Signed.

**Comment by cclauss** [comment]
Kinda silly to force a DOC on the deletion of two lines of configuration.

**Comment by alexvicegrab** [comment]
@cclauss, thanks!
Re DCO, the rules are made by Hyperledger, and it's not an unusual requirement for OS projects of this scale

**Pull request merged**
